### ISSUE TITLE
https://github.com/F3real/ctf_solutions/blob/master/2019/247ctf/secret_sol.py#L137

### ISSUE THREAD

**Issue by evandrix** [F3real/ctf_solutions#2]
https://f3real.github.io/247ctf_1.html#the-secret-lock
"Interestingly biggest issue I had was with getting results from Z3 model so in the end I just manually modified printed output in notepad and gotten the flag."

FTFY:
```
if s.check() == sat:
  model = s.model()
  print("".join(map(chr,[model.evaluate(xx).as_long() for xx in x])))
else: print("unsat")
```

**Comment by F3real** [comment]
Thanks for the suggestion.
